### ISSUE TITLE
Link na doplnění P6736

### ISSUE THREAD

**Issue by jkjkjkjkjk** [mormegil-cz/POI-Importer.github.io#1]
Je-li shoda k existující WD položce, kde není vyplněno P6736, přidat tlačítko (příp přes Import Data) na doplnění P6736 do existující WD položky, tedy syntax 
["entityId(?)|P6736|"{id}(?)" + refAppend];

**Comment by mormegil-cz** [comment]
Ono asi dává smysl umožnit založení nové položky i v případě nalezení nějakého potenciálního cíle, který může být špatně, takže asi vždycky přidat sloupecek s tlačítky + vpravo místo přepínání funkce odkazu v tom nadpisu...

**Comment by jkjkjkjkjk** [comment]
Ano, dobrá poznámka, ne vždy se trefí ten správný cíl (typicky křížek u kapličky).

**Comment by VojtechDostal** [comment]
Tohle je přesně issue, které by mě přimělo párování provádět (zjednodušilo by to výrazně celý proces). Díky JK za vytvoření!

**Comment by mormegil-cz** [comment]
Nakonec vcelku jednoduché řešení umožňující vyrobit QS dávku přidávající to jediné tvrzení. (Možná by hezčí bylo otevřít přímo editaci WD, ale k tomu IMHO žádné rozhraní neexistuje, muselo by se buď spáchat nějaké udělátko, které by takové rozhraní přidávalo, nebo to doimplementovat přímo do Wikibase; každopádně supersložité, neřeším.)

Zakládat novou položku lze vždycky, i pokud se nějaké mapování našlo; výběr _jiné_ položky je asi moc složitý usecase pro takovýhle základní nástroj; to už se holt asi musí doladit ručními editacemi WD.

**Comment by VojtechDostal** [comment]
Boží, funguje mi to!
