### ISSUE TITLE
Zvláštní nespárování dvou památek

### ISSUE THREAD

**Issue by VojtechDostal** [mormegil-cz/POI-Importer.github.io#15]
Trochu jsem systematicky procházel památky v okrese Plzeň-sever, o němž pořizovatel databáze Drobné památky tvrdí, že je v podstatě systematicky projitý a tedy z jejich strany kompletně zmapovaný.[ Seznam plastik v tomto okrese bez identifikátoru](https://w.wiki/6Fc).

Hned první jsou boží muka, která jsem dohledal v obou databázích:
https://www.wikidata.org/wiki/Q37818641
https://www.drobnepamatky.cz/node/2015

Ovšem POI importer je nepáruje (špendlík hodnotí jako "missing poi"). [Odkaz na mapu](https://tools.wmflabs.org/poiimport/#map=17/49.9856/13.2453&datasets=DrobnePamatky&settings=hideCompletePOI)
Podle souřadnic jsou (jen) 44 metrů od sebe, je to již více než práh, který bere v potaz POI importer pro vzájemnou blízkost? Nebo co ještě může hrát roli?

**Comment by mormegil-cz** [comment]
Ano. Dovolený limit vzdálenosti je [u Drobných památek nastavený na 30 m](https://github.com/mormegil-cz/POI-Importer.github.io/blob/wip-drobnepamatky-wikidata/datasets/czechia-drobnepamatky/dataset.json#L6).

**Comment by VojtechDostal** [comment]
Aha, asi to dává smysl, i když možná ještě deset dvacet metrů k dobru by si ta tolerance od oka zasloužila (ale nevím, třeba jsi to nějak testoval a pak už tam vylézá příliš mnoho falešných párů).

**Comment by mormegil-cz** [comment]
Ne, nijak zvlášť jsem to netestoval, klidně to můžu zvýšit, pokud ti přijde, že to je rozumné. Já bych si tedy myslel, že u drobných památek je 30 m tak nějak akorát, zejména tady, kde ta ostatní kritéria mají do jednoznačnosti/dokonalosti daleko. Ale určitě máš větší praktické zkušenosti, takže klidně můžu zkusit nastavit to na… 45 metrů? A když uvidíš, že se to spíš zhoršilo, tak to můžeme vrátit na 30 nebo jinak doladit.
