### ISSUE TITLE
Nástroj občas nenačte identifikátory z Wikidat ač už tam jsou

### ISSUE THREAD

**Issue by VojtechDostal** [mormegil-cz/POI-Importer.github.io#16]
V posledním týdnu se mi stává, že POIImporter nenačte identifikátory z příslušné položky z Wikidat (ukáže N/A) ačkoliv tam už dávno jsou. Může to souviset s #13 protože někdy tou dobou se to začalo vyskytovat... Omlouvám se, že zase prudím :) 

<img width="460" alt="Bez názvu" src="https://user-images.githubusercontent.com/21329813/61644773-9de32080-aca5-11e9-80aa-0e5f040bfea0.png">

**Comment by mormegil-cz** [comment]
Hele jako divný to rozhodně je, ale skoro bych tvrdil, že problém není na mém… vysílači. Jakkoli se to může nepoučenému laikovi zdát, [ta položka prostě ID DrobnýchPamátek nemá](https://w.wiki/6Ne). Jako WTfakt. :-? Vidíš tam někde něco, co přehlížím?

**Comment by VojtechDostal** [comment]
Huh. Nebude to náhodou další manifestace tohoto?
https://phabricator.wikimedia.org/T228640
