### ISSUE TITLE
drobnepamatky.cz

### ISSUE THREAD

**Issue by JAnDud** [mormegil-cz/POI-Importer.github.io#20]
Šlo by to prosím opět aktualizovat?
https://www.drobnepamatky.cz/files/drobnepamatky.csv

**Comment by mormegil-cz** [comment]
On to ještě někdo používá? Já myslel, že už všichni přešli na různé modernější nástroje :-)

**Comment by JAnDud** [comment]
Díky. 
Pokud víš o jiném nástroji, který to zobrazí v mapě...
nevím, zda to k něčemu bude, ale se starými daty to ani nejde vyzkoušet ;-)
