### ISSUE TITLE
Mapa někdy načte špendlíky v jiné oblasti, než v té, kterou jsem zrovna zazoomoval

### ISSUE THREAD

**Issue by VojtechDostal** [mormegil-cz/POI-Importer.github.io#3]
Někdy při používání mapy zůstávají špendlíky v načtené oblasti šedé. Stačí ovšem odzoomovat a popojet kousek stranou a tam obvykle bývají špendlíky načtené. Všiml jsem si, že obvykle jsou tyto načtené špendlíky kousek na severozápad od oblasti, kterou jsem měl zazoomovanou. Mám dojem, že podobný problém hlásil na FB i Frettie.

**Comment by jkjkjkjkjk** [comment]
Také mi to takto dělá, F5 nepomáhá.

**Comment by VojtechDostal** [comment]
Dnes mi to již nedělá, nevím proč.

**Comment by mormegil-cz** [comment]
Ono to v zásadě je vždycky tím, že chcípne dotaz na WQS. Zřejmě je v importeru bug, že se z takové situace moc nevzpamatuje a pomůže až F5, to by se dalo určitě opravit/vylepšit. Ale to, že WQS je náladový, moc nevyřešíme (leda nějakým opakováním nezdařených dotazů). (Třeba včera mi chvílemi vracel _HTTP 431 Request Header Fields Too Large_, což tedy fakt netuším, co mělo znamenat; ([cosi podobného](https://phabricator.wikimedia.org/T216590))).

Jinak „severozápad“ znamená jen to, že Importer načítá vždy devět elementárních „dlaždic“ okolo zobrazeného středu, přičemž se jede zleva zhora doprava dolů, takže pokud WQS chcípe, je pravděpodobnější, že budou načtené špendlíky nahoře, příp. vlevo.

**Comment by VojtechDostal** [comment]
Už se mi to dlouho nestalo. Asi vyřešeno :)
