### ISSUE TITLE
Již namatchované identifikátory by se již neměly nabízet

### ISSUE THREAD

**Issue by VojtechDostal** [mormegil-cz/POI-Importer.github.io#9]
Myslím si, že pokud již je nějaký identifikátor namatchovaný do Wikidat (a je tedy přiřazen k nějaké položce), už by se neměl nabízet jeho špendlík. Včera jsem do Wikidat naimportoval zbylé drobné památky z celé Prahy, teda myslím, ale stále se tam špendlíky ukazují.

**Comment by mormegil-cz** [comment]
Nerozumím. Tím se myslí #8, který se zapíná zaškrtávátkem _Hide matched POI_ v _Settings_, ne? Nebo je tím myšleno něco jiného?

**Comment by VojtechDostal** [comment]
Teď trochu zlobí databáze, ale postup je takovýhle:

1. najet na Prahu
2. zaškrtnout všechny tři "hide..." v možnostech
3. zůstanou stále špendlíky v Praze

Přitom by ale podle mně už v Praze žádné špendlíky být neměly, všechny drobné památky v Praze jsem myslím naimportoval včera v noci.

**Comment by mormegil-cz** [comment]
Možná to bude u některých konkrétních i něčím jiným, ale nejspíše půjde o to, že položky, na které je ta památka namapovaná, nevyhovují [definici filtru v tom datasetu](https://github.com/mormegil-cz/POI-Importer.github.io/blob/wip-drobnepamatky-wikidata/datasets/czechia-drobnepamatky/dataset.json). Namátkovou kontrolou jsem našel dva reprezentativní případy:
- [kameny se stopami](https://www.wikidata.org/wiki/Q64816232) s typem „zeměpisný objekt“ (což je tedy zatraceně obecná třída, skoro bych řekl, že by tam mělo být něco specifičtějšího, třeba Q1746392 nebo něco podobného); ale není se za co stydět, Drobné památky tady měly _Něco jiného_, což jsem ani nevěděl, jak zpracovat, takže jsem tam nechal otazník (a TODO), takže se skoro divím, že se to povedlo naimportovat. :-)
- [rotunda svatého Martina](https://www.wikidata.org/wiki/Q12049842) s typem „kostel+rotunda“, což je IMHO vůbec poněkud nedrobná památka… (Drobné památky tam měly kapli…)

Původně jsem tam měl nějaký super obecný filtr všech potomků něčeho nevímčehopřesně, ale ten dotaz byl naprosto nepoužitelně pomalý, takže teď je tam seznam odpovídající zhruba typům památek, které evidují na DrobnýchPamátkách, rozšířený o pár věcí, na které narazil jk. Ale v jednotlivých případech to sedět nebude; řešením je patrně rozšířit ten filtr o ty další běžně používané třídy, pokud jsou ty třídy správně.

**Comment by VojtechDostal** [comment]
Trochu rozumím ale je to pro mě složité :). Třeba mi mapa nabízí červený pin pro památku "Obrázek svatého Martina nad portálem kostela svatého Martina ve zdi" která má číslo 24762. Myslím, že nástroj by se mohl kouknout do Wikidat, zjistil by, že už tam existuje položka Q64815498 s tímto identifikátorem, a špendlík skrýt.

**Comment by mormegil-cz** [comment]
Ten nástroj dělá přesně to, ale nemůže pro každý jednotlivý špendlík udělat jedno query do Wikidat, to bychom asi položili WQS a hlavně by to trvalo týden, než by se to načetlo.

Dělá se to hromadně po dlaždicích a ten dotaz načítá položky z Wikidat podle toho definovaného filtru. Ale teď mě napadlo jednoduché řešení: Do těch položek zařadit _všechny_, které už mají identifikátor z drobných památek, tím se zajistí, že všechny _už spárované_ tam budou, bez ohledu na to, na co jsou napárované. (Jakože ten „zeměpisný objekt“ je IMHO pořád špatně, ostatně viz i ten vykřičníček u P6736… ;-) )

**Comment by VojtechDostal** [comment]
Aha, super řešení. O zeměpisných objektech vím, tuhle instanci jsem dával ke všem objektům co tam měli "Něco jiného", je to zhruba deset položek. Aspoň to nedělá vykřičník u P625. Ale je to dočasný řešení, vím o tom.

**Comment by mormegil-cz** [comment]
V zásadě si myslím, že by mělo být vyřešeno. To, co zbývá, vypadá opravdu spíš na chyby v datech: Namátkovou kontrolou jsem našel čtyři problémy na Wikidatech či Drobných památkách (třeba [špatné souřadnice rotundy na Vyšehradě](https://www.wikidata.org/wiki/Special:Diff/969780834)). Zkus na to kouknout, jestli narazíš na nějaký další systematický problém nebo nějaký konkrétní problematický případ, dej vědět.
